require('dotenv').config();
const express=require('express');
const cors=require('cors');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const multer=require('multer');
const path=require('path');
const fs=require('fs');
const {Pool}=require('pg');

const app=express();
const PORT=process.env.PORT||3000;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const uploadDir=path.join(__dirname,'public','uploads'); fs.mkdirSync(uploadDir,{recursive:true});
const storage=multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase(); cb(null,Date.now()+'-'+Math.random().toString(36).slice(2)+ext)}});
const upload=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(jpeg|png|webp|gif)$/.test(file.mimetype))});
app.use(cors());app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,'public')));

async function init(){
 await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(180) UNIQUE NOT NULL,phone VARCHAR(30),password_hash TEXT NOT NULL,role VARCHAR(20) NOT NULL CHECK(role IN ('buyer','seller','admin')),created_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS products(id SERIAL PRIMARY KEY,seller_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name VARCHAR(220) NOT NULL,description TEXT,category VARCHAR(80) NOT NULL,price NUMERIC(12,2) NOT NULL CHECK(price>=0),old_price NUMERIC(12,2),stock INT NOT NULL DEFAULT 0 CHECK(stock>=0),image TEXT,rating NUMERIC(2,1) DEFAULT 4.3,active BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,order_number VARCHAR(40) UNIQUE NOT NULL,buyer_id INT NOT NULL REFERENCES users(id),total NUMERIC(12,2) NOT NULL,shipping_name VARCHAR(120) NOT NULL,shipping_phone VARCHAR(30) NOT NULL,shipping_address TEXT NOT NULL,payment_method VARCHAR(30) NOT NULL DEFAULT 'COD',created_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS seller_orders(id SERIAL PRIMARY KEY,order_id INT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,seller_id INT NOT NULL REFERENCES users(id),total NUMERIC(12,2) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'Confirmed',created_at TIMESTAMPTZ DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS order_items(id SERIAL PRIMARY KEY,seller_order_id INT NOT NULL REFERENCES seller_orders(id) ON DELETE CASCADE,product_id INT NOT NULL REFERENCES products(id),product_name VARCHAR(220) NOT NULL,price NUMERIC(12,2) NOT NULL,quantity INT NOT NULL CHECK(quantity>0));
 CREATE INDEX IF NOT EXISTS idx_products_seller ON products(seller_id); CREATE INDEX IF NOT EXISTS idx_seller_orders_seller ON seller_orders(seller_id);`);
}
function tokenFor(u){return jwt.sign({id:u.id,role:u.role,name:u.name,email:u.email},process.env.JWT_SECRET||'dev-secret-change-me',{expiresIn:'7d'})}
function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Login required'});req.user=jwt.verify(h.slice(7),process.env.JWT_SECRET||'dev-secret-change-me');next()}catch(e){res.status(401).json({error:'Invalid or expired login'})}}
function role(...roles){return (req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Not allowed'})}
const q=(text,params)=>pool.query(text,params);

app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password,phone,role='buyer'}=req.body;if(!name||!email||!password)return res.status(400).json({error:'Name, email and password are required'});if(!['buyer','seller'].includes(role))return res.status(400).json({error:'Invalid role'});const hash=await bcrypt.hash(password,12);const r=await q('INSERT INTO users(name,email,phone,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id,name,email,phone,role',[name,email.toLowerCase(),phone||'',hash,role]);res.json({user:r.rows[0],token:tokenFor(r.rows[0])})}catch(e){res.status(400).json({error:e.code==='23505'?'Email already registered':e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=req.body;const r=await q('SELECT * FROM users WHERE email=$1',[String(email||'').toLowerCase()]);if(!r.rows[0]||!(await bcrypt.compare(password||'',r.rows[0].password_hash)))return res.status(401).json({error:'Invalid email or password'});const u=r.rows[0];res.json({user:{id:u.id,name:u.name,email:u.email,phone:u.phone,role:u.role},token:tokenFor(u)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/auth/me',auth,async(req,res)=>{const r=await q('SELECT id,name,email,phone,role FROM users WHERE id=$1',[req.user.id]);res.json({user:r.rows[0]})});

app.get('/api/products',async(req,res)=>{try{const {search='',category='All',sort='new'}=req.query;let sql=`SELECT p.*,u.name seller_name FROM products p JOIN users u ON u.id=p.seller_id WHERE p.active=true`;const params=[];if(search){params.push('%'+search+'%');sql+=` AND (p.name ILIKE $${params.length} OR p.description ILIKE $${params.length})`}if(category&&category!=='All'){params.push(category);sql+=` AND p.category=$${params.length}`}sql+=sort==='priceLow'?' ORDER BY p.price ASC':sort==='priceHigh'?' ORDER BY p.price DESC':' ORDER BY p.created_at DESC';const r=await q(sql,params);res.json(r.rows)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/products/:id',async(req,res)=>{const r=await q('SELECT p.*,u.name seller_name FROM products p JOIN users u ON u.id=p.seller_id WHERE p.id=$1 AND p.active=true',[req.params.id]);if(!r.rows[0])return res.status(404).json({error:'Product not found'});res.json(r.rows[0])});
app.post('/api/products',auth,role('seller','admin'),upload.single('image'),async(req,res)=>{try{const {name,description,category,price,old_price,stock}=req.body;if(!name||!category||price===undefined)return res.status(400).json({error:'Name, category and price are required'});const image=req.file?'/uploads/'+req.file.filename:(req.body.image||'');const r=await q('INSERT INTO products(seller_id,name,description,category,price,old_price,stock,image) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[req.user.id,name,description||'',category,Number(price),old_price?Number(old_price):null,Number(stock||0),image]);res.json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.put('/api/products/:id',auth,role('seller','admin'),upload.single('image'),async(req,res)=>{try{const own=await q('SELECT * FROM products WHERE id=$1 AND ($2::int= seller_id OR $3=true)',[req.params.id,req.user.id,req.user.role==='admin']);if(!own.rows[0])return res.status(404).json({error:'Product not found'});const p=own.rows[0],b=req.body;const image=req.file?'/uploads/'+req.file.filename:(b.image!==undefined?b.image:p.image);const r=await q('UPDATE products SET name=$1,description=$2,category=$3,price=$4,old_price=$5,stock=$6,image=$7,active=$8 WHERE id=$9 RETURNING *',[b.name??p.name,b.description??p.description,b.category??p.category,Number(b.price??p.price),b.old_price===''?null:Number(b.old_price??p.old_price),Number(b.stock??p.stock),image,b.active===undefined?p.active:b.active!=='false',req.params.id]);res.json(r.rows[0])}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/products/:id',auth,role('seller','admin'),async(req,res)=>{const r=await q('UPDATE products SET active=false WHERE id=$1 AND ($2::int=seller_id OR $3=true) RETURNING id',[req.params.id,req.user.id,req.user.role==='admin']);if(!r.rows[0])return res.status(404).json({error:'Product not found'});res.json({ok:true})});
app.get('/api/seller/products',auth,role('seller','admin'),async(req,res)=>{const r=await q('SELECT * FROM products WHERE seller_id=$1 ORDER BY created_at DESC',[req.user.id]);res.json(r.rows)});

app.post('/api/orders',auth,role('buyer','admin'),async(req,res)=>{const client=await pool.connect();try{const {items,shipping,payment_method='COD'}=req.body;if(!Array.isArray(items)||!items.length)return res.status(400).json({error:'Cart is empty'});if(!shipping?.name||!shipping?.phone||!shipping?.address)return res.status(400).json({error:'Shipping details are required'});await client.query('BEGIN');const ids=[...new Set(items.map(x=>Number(x.productId)))];const pr=await client.query('SELECT * FROM products WHERE id=ANY($1::int[]) AND active=true FOR UPDATE',[ids]);const map=new Map(pr.rows.map(p=>[p.id,p]));const groups=new Map();let grand=0;for(const item of items){const p=map.get(Number(item.productId));const qty=Number(item.quantity);if(!p||!Number.isInteger(qty)||qty<1)throw new Error('Invalid product or quantity');if(p.stock<qty)throw new Error(`${p.name} has only ${p.stock} item(s) left`);const line=Number(p.price)*qty;grand+=line;if(!groups.has(p.seller_id))groups.set(p.seller_id,[]);groups.get(p.seller_id).push({p,qty,line});}
 const orderNo='SS'+Date.now().toString().slice(-10);const o=await client.query('INSERT INTO orders(order_number,buyer_id,total,shipping_name,shipping_phone,shipping_address,payment_method) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[orderNo,req.user.id,grand,shipping.name,shipping.phone,shipping.address,payment_method]);
 for(const [sellerId,lines] of groups){const total=lines.reduce((a,x)=>a+x.line,0);const so=await client.query('INSERT INTO seller_orders(order_id,seller_id,total) VALUES($1,$2,$3) RETURNING id',[o.rows[0].id,sellerId,total]);for(const x of lines){await client.query('INSERT INTO order_items(seller_order_id,product_id,product_name,price,quantity) VALUES($1,$2,$3,$4,$5)',[so.rows[0].id,x.p.id,x.p.name,x.p.price,x.qty]);await client.query('UPDATE products SET stock=stock-$1 WHERE id=$2',[x.qty,x.p.id])}}
 await client.query('COMMIT');res.json({orderNumber:orderNo,total:grand})}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
app.get('/api/orders/my',auth,role('buyer','admin'),async(req,res)=>{const r=await q(`SELECT o.order_number,o.total,o.shipping_name,o.shipping_phone,o.shipping_address,o.payment_method,o.created_at,so.id seller_order_id,so.status,so.total seller_total,u.name seller_name,COALESCE(json_agg(json_build_object('name',oi.product_name,'price',oi.price,'quantity',oi.quantity)) FILTER (WHERE oi.id IS NOT NULL),'[]') items FROM orders o JOIN seller_orders so ON so.order_id=o.id JOIN users u ON u.id=so.seller_id LEFT JOIN order_items oi ON oi.seller_order_id=so.id WHERE o.buyer_id=$1 GROUP BY o.id,so.id,u.id ORDER BY o.created_at DESC`,[req.user.id]);res.json(r.rows)});
app.get('/api/seller/orders',auth,role('seller','admin'),async(req,res)=>{const r=await q(`SELECT so.id,so.status,so.total,so.created_at,o.order_number,o.shipping_name,o.shipping_phone,o.shipping_address,o.payment_method,u.name buyer_name,u.email buyer_email,COALESCE(json_agg(json_build_object('name',oi.product_name,'price',oi.price,'quantity',oi.quantity)) FILTER (WHERE oi.id IS NOT NULL),'[]') items FROM seller_orders so JOIN orders o ON o.id=so.order_id JOIN users u ON u.id=o.buyer_id LEFT JOIN order_items oi ON oi.seller_order_id=so.id WHERE so.seller_id=$1 GROUP BY so.id,o.id,u.id ORDER BY so.created_at DESC`,[req.user.id]);res.json(r.rows)});
app.patch('/api/seller/orders/:id/status',auth,role('seller','admin'),async(req,res)=>{const allowed=['Confirmed','Packed','Shipped','Delivered','Cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Invalid status'});const r=await q('UPDATE seller_orders SET status=$1 WHERE id=$2 AND seller_id=$3 RETURNING *',[req.body.status,req.params.id,req.user.id]);if(!r.rows[0])return res.status(404).json({error:'Order not found'});res.json(r.rows[0])});
app.get('/api/seller/stats',auth,role('seller','admin'),async(req,res)=>{const p=await q('SELECT COUNT(*)::int count,COALESCE(SUM(price*stock),0)::numeric inventory_value FROM products WHERE seller_id=$1 AND active=true',[req.user.id]);const o=await q(`SELECT COUNT(*)::int orders,COALESCE(SUM(total),0)::numeric sales FROM seller_orders WHERE seller_id=$1 AND status<>'Cancelled'`,[req.user.id]);const pending=await q(`SELECT COUNT(*)::int count FROM seller_orders WHERE seller_id=$1 AND status IN ('Confirmed','Packed')`,[req.user.id]);res.json({products:p.rows[0],orders:o.rows[0],pending:pending.rows[0].count})});

app.get('/api/health',async(req,res)=>{try{await q('SELECT 1');res.json({ok:true})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.get('/*splat',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
init().then(()=>app.listen(PORT,()=>console.log(`ShopSphere running on http://localhost:${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
